//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemestryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MendelevDB
    {
        public int AtomicNumber { get; set; }
        public string Element { get; set; }
        public string Symbol { get; set; }
        public Nullable<double> AtomicMass { get; set; }
        public Nullable<int> NumberofNeutrons { get; set; }
        public Nullable<int> NumberofProtons { get; set; }
        public Nullable<int> NumberofElectrons { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> Group { get; set; }
        public string Phase { get; set; }
        public string Radioactive { get; set; }
        public string Natural { get; set; }
        public string Metal { get; set; }
        public string Nonmetal { get; set; }
        public string Metalloid { get; set; }
        public string Type { get; set; }
        public Nullable<double> AtomicRadius { get; set; }
        public Nullable<double> Electronegativity { get; set; }
        public Nullable<double> FirstIonization { get; set; }
        public Nullable<double> Density { get; set; }
        public Nullable<double> MeltingPoint { get; set; }
        public Nullable<double> BoilingPoint { get; set; }
        public Nullable<int> NumberOfIsotopes { get; set; }
        public string Discoverer { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> SpecificHeat { get; set; }
        public Nullable<int> NumberofShells { get; set; }
        public Nullable<int> NumberofValence { get; set; }
        public string Image { get; set; }
    }
}
